name: dailybudget
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.3
  intl: ^0.20.2
  flutter_lints: ^5.0.0
  flutter_bloc: ^9.1.1
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  window_size: ^0.1.0
  speech_to_text: ^7.2.0
  clock: ^1.1.2
  path_provider: ^2.1.5
  encrypt: ^5.0.3
  google_sign_in: ^6.1.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.8
  firebase_core: ^3.13.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


  generate: true
